# Makefile for mandelbrot GPU

CC = clang
CCFLAGS += -fopenmp=libomp -fopenmp-targets=nvptx64-nvidia-cuda -Xopenmp-target=nvptx64-nvidia-cuda -march=sm_80

all: mandelbrot

mandelbrot: mandelbrot.o
	$(CC) $(CCFLAGS) -g -o $@ $^ utils/lodepng.c

mandelbrot.o: mandelbrot.c
	$(CC) $(CCFLAGS) -g -c -o $@ $^

clean:
	@rm -rf *.o *~ *# $(EXEC) *png mandelbrot
